// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EditSpecialtyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void editSpecialty() {
    // Test name: EditSpecialty
    // Step # | name | target | value | comment
    // 1 | open | /petclinic/ |  | 
    driver.Navigate().GoToUrl("https://client.sana-commerce.dev/petclinic/");
    // 2 | setWindowSize | 1074x676 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1074, 676);
    // 3 | click | css=li:nth-child(5) > a |  | 
    driver.FindElement(By.CssSelector("li:nth-child(5) > a")).Click();
    // 4 | click | css=tr:nth-child(10) .editSpecialty |  | 
    driver.FindElement(By.CssSelector("tr:nth-child(10) .editSpecialty")).Click();
    // 5 | click | id=name |  | 
    driver.FindElement(By.Id("name")).Click();
    // 6 | type | id=name | test1 | 
    driver.FindElement(By.Id("name")).SendKeys("test1");
    // 7 | click | css=.updateSpecialty |  | 
    driver.FindElement(By.CssSelector(".updateSpecialty")).Click();
  }
}
