// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoadPetTypesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loadPetTypes() {
    // Test name: LoadPetTypes
    // Step # | name | target | value | comment
    // 1 | open | /petclinic/ |  | 
    driver.Navigate().GoToUrl("https://client.sana-commerce.dev/petclinic/");
    // 2 | setWindowSize | 1074x676 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1074, 676);
    // 3 | click | css=li:nth-child(4) > a |  | 
    driver.FindElement(By.CssSelector("li:nth-child(4) > a")).Click();
  }
}
