// Generated by Selenium IDE
using NUnit.Framework;
using Lab_4.PageObjects;
using Lab_4.Components;
using Lab_4.Factory;

namespace Lab_4
{
    [TestFixture]
    public class AddPetTypeTest : Base
    {
        [Test]
        public void AddPetType()
        {
            NavigationComponent option = Component.Button;
            PetTypesPageObjects pageObject = new PetTypesPageObjects(driver);

            option.OpenPetTypes();

            pageObject.OpenPetTypeAddForm();
            pageObject.AddPetType("Akita");
            Assert.True(pageObject.IsNameCorrect("Akita"));
        }
    }
}
