// Generated by Selenium IDE
using NUnit.Framework;
using Lab_4.PageObjects;

namespace Lab_4
{
    [TestFixture]
    public class AddPetTypeTest : Base
    {
        [Test]
        public void AddPetType()
        {
            PetTypesPageObjects pageObject = new PetTypesPageObjects(driver);

            pageObject.OpenPetTypes();
            pageObject.OpenPetTypeAddForm();
            pageObject.AddPetType("Akita");
            Assert.True(pageObject.IsNameCorrect("Akita"));
        }
    }
}
